Edit DG for listi, findi and edito + Added UML sequence diagrams for them
AY2223S1-CS2103T-W15-3/tp pull request #138
Opened 2022-10-27 11:19 UTC by melissaharijanto

# In this PR
1. I added UML sequence diagrams for all three commands. Although they will be reflected in `Files Changed`, I will also attach them here.
2. I fixed a bug in `EditOrderCommand#execute()` to make model call `getSortedOrdersList()` instead of `getFilteredOrdersList()`.
3. Added implementation details for the three commands.

2022-10-27 13:30 UTC, donljh requested changes
Good work on the sequence diagrams, but I think for any of the objects where they are marked as deleted (the 'X'), the lifeline should terminate. Otherwise I don't see anything wrong for now!

2022-10-27 15:56 UTC, donljh requested changes
Generally looks good. Suggested a few similar changes across the different sections

2022-10-27 15:56 UTC, donljh commented on docs/DeveloperGuide.md
> +  - Cons: Unable to filter specific items.
I think for design considerations, we have to state which part of the design implementation that we are considering, i.e. `How the listi command executes`, before offering the alternatives. Maybe it would be good to include something similar?

2022-10-27 15:56 UTC, donljh commented on docs/DeveloperGuide.md
> +The find item feature allows the user to find an `Item` by keyword/s given by the user.
To be more specific, maybe you want to rename `Item` to `InventoryItem` here. Also, to be more in line with the functionality of the feature, you can maybe say `allows the user to find InventoryItem(s)`

2022-10-27 15:56 UTC, donljh commented on docs/DeveloperGuide.md
> +The list item feature is executed by the `ListItemsCommand`. It extends `Command`.
Can consider changing it to `The list item feature is supported by...`

2022-10-27 15:56 UTC, donljh commented on docs/DeveloperGuide.md
> +The find item command is executed by `FindItemCommand`. It extends `Command`.
Can consider changing to `The find item feature is supported by...`

2022-10-27 15:56 UTC, donljh commented on docs/DeveloperGuide.md
> +    - Cons: Harder to implement.
Same as the comment regarding design considerations above

2022-10-27 15:56 UTC, donljh commented on docs/DeveloperGuide.md
This implementation seems to be inconsistent from the other sections (the portion where it says `This feature is supported by...`

2022-10-27 15:56 UTC, donljh commented on docs/DeveloperGuide.md
> +The edit order feature is executed by `EditOrderCommand`. It extends `Command`.
Same here

2022-10-27 16:04 UTC, melissaharijanto commented on docs/DeveloperGuide.md
> +  - Cons: Unable to filter specific items.
oh the 'aspect' part is it? i'll add that in, thanks for telling me! :D

2022-10-27 18:59 UTC, donljh approved these changes
Should be good for now!

2022-10-28 03:13 UTC, Jiacheng-y approved these changes

2022-10-28 03:36 UTC, merged