Update User Guide with features: listo and findo
AY2223S1-CS2103T-W15-3/tp pull request #39
Opened 2022-09-26 11:09 UTC by janelleljt

2022-09-26 11:28 UTC, sohenze approved these changes
Looks good

2022-09-27 17:46 UTC, donljh requested changes

2022-09-27 17:46 UTC, donljh commented on docs/UserGuide.md
> +### Locating persons by name: `findo`
I think you might have forgotten to change 'Locating persons by name' to the relevant title here

2022-09-27 17:46 UTC, donljh commented on docs/UserGuide.md
>  Format: `find KEYWORD [MORE_KEYWORDS]`
Command here should be 'findo' instead of 'find'

2022-09-27 17:46 UTC, donljh commented on docs/UserGuide.md
> +* The search is case-insensitive. e.g `keychain` will match `Kans`
I think you meant to change 'Hans' to 'Keychain' instead of 'Kans' here

2022-09-27 17:46 UTC, donljh commented on docs/UserGuide.md
>  * Persons matching at least one keyword will be returned (i.e. `OR` search).
'Persons' should be 'Orders with item names' instead

2022-09-27 17:46 UTC, donljh commented on docs/UserGuide.md
> +* `find apple keychain` returns `apple painting`, `banana keychain`<br>
Like above, this should be 'findo' instead of 'find'

2022-09-27 17:46 UTC, donljh commented on docs/UserGuide.md
> +**findo** | `find KEYWORD [MORE_KEYWORDS]`
'findo' instead of 'find' here as well

2022-09-29 02:44 UTC, donljh approved these changes

2022-09-29 03:24 UTC, merged